name: Update Coverage Stats

on:
  # Runs on push to main/master
  push:
    branches: [ main, master ]
  # Runs on merged PRs
  pull_request:
    types: [closed]
    branches: [ main, master ]

jobs:
  update-coverage:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        # Full git history for commits
        fetch-depth: 0
        # Token with write permissions
        token: ${{ secrets.COVERAGE_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run tests and update coverage
      run: |
        python scripts/update_coverage.py

    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "docs: update test coverage stats [skip ci]"
        git push 